config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'namespaces#index'

  namespace :api, defaults: { format: 'json' } do
    scope module: :v1 do
      get '', to: 'root#index', as: :root

      resources :namespaces, only: %i[index show] do
        resources :pages, only: %i[index show]
      end
    end
  end

  get 'new' => 'namespaces#new'
  get 'search' => 'search#index'

  # Occupy remaining root namespace
  # (place route declarations above this)

  resources :namespaces, path: '' do
    member do
      get 'edit'
    end

    resources :pages, path: '' do
      collection do
        get 'random'
      end

      member do
        get 'rendered'
        get 'source'
        get 'markdown'
        get 'urls'
        get 'next'
        get 'previous'
      end

      resources :uploads, only: %i[index create]
      resources :versions, only: [:index] do
        member do
          post 'restore'
        end
      end
    end
  end
end

app/views/pages/_form.html.erb
<%= form_for [@namespace, @page], html: {
  class: 'form', data: { upload: @page.persisted? ? namespace_page_uploads_path(@namespace, @page) : '' }
} do |f| %>
  <%= render 'common/errors', resource: @page %>

  <div class='field'>
    <%= f.label :slug, 'ID' %>
    <%= f.text_field :slug, required: true %>
  </div>

  <div class='field'>
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: 'Title', autofocus: true %>
  </div>

  <div class='field'>
    <%= f.label :mode %>
    <%= f.select :mode, Page.modes.keys.to_a %>
  </div>

  <div class='submit'>
    <% if @page.persisted? %>
      <%= link_to 'Delete', [@namespace, @page], method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-dangerous' %>
    <% end %>

    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/pages/_stub.html.erb
<% if namespace.locked? && !logged_in? %>
  <div class='item'>
    <div class='item__title'>
      Log in to view this page
    </div>
  </div>
<% else %>
  <%= link_to namespace_page_path(namespace, page), class: 'item' do %>
    <% if page.title.present? %>
      <div class='item__title'>
        <%= page.title %>
      </div>
    <% end %>

    <% if page.preview.present? %>
      <div class='item__preview'>
        <%= page.preview %>
      </div>
    <% end %>

    <div class='item__meta'>
      <%= time_tag page.updated_at, class: 'item__updated-at' do %>
        <% if page.updated_at.between?(3.days.ago, Time.now) %>
          Updated <%= time_ago_in_words page.updated_at %> ago
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/pages/all.html.erb
<% @pages.each do |page| %>
  <%= content_tag_for :div, page do %>
    <%= link_to "#{page} /#{page.slug}", page %>
  <% end %>
<% end %>

app/views/pages/edit.html.erb
<% content_for(:title) { "Editing #{@namespace} / #{@page}" } %>

<% content_for :breadcrumb do %>
  <%= link_to 'Root', :root %>
  <%= link_to @namespace, @namespace %>
  <%= link_to @page, namespace_page_path(@namespace, @page) %>
  <%= content_tag :span, 'Settings' %>
<% end %>

<%= render 'form' %>

app/views/pages/index.html.erb
<% content_for(:title) { @namespace.name } %>

<% if @namespace.locked? %>
  <div class='namespace-state'>
    <%= material_icon.lock.md_18 %>
  </div>
<% end %>

<% content_for :breadcrumb do %>
  <%= link_to 'Root', :root %>
  <%= content_tag :span, @namespace %>
<% end %>

<% content_for :contextual do %>
  <% toggled_status(params[:status]).tap do |status| %>
    <%= link_to "View #{status.titleize}", namespace_path(@namespace, status: status) %>
  <% end %>
  <%= link_to 'Settings', edit_namespace_path(@namespace) %>
  <%= render 'search/form' %>
<% end %>

<% content_for :actions do %>
  <%= link_to material_icon.shuffle, random_namespace_pages_path(@namespace) %>
<% end %>

<% if logged_in? %>
  <div class='page-add'>
    <div
      class='page js-page-editor'
      data-url='<%= url_for [@namespace, Page.new] %>'
      data-autosave='false'
      data-create='true'
    >
      <!-- Rendered client-side -->
    </div>
  </div>
<% end %>

<div class='pages'>
  <% @pages.each do |page| %>
    <%= render 'stub', namespace: @namespace, page: page %>
  <% end %>
</div>

<%= paginate @pages %>

app/views/pages/new.html.erb
<% content_for(:title) { "Add a page to #{@namespace}" } %>

<% content_for :breadcrumb do %>
  <%= link_to 'Root', :root %>
  <%= link_to @namespace, @namespace %>
  <%= content_tag :span, 'New Page'%>
<% end %>

<%= render 'form' %>

app/views/pages/rendered.html.erb
<% content_for(:title) { "#{@namespace} / #{@page}" } %>

<div class='page page--rendered'>
  <%= @page.html.html_safe %>
</div>

app/views/pages/show.html.erb
<% content_for(:title) { "#{@namespace} / #{@page}" } %>

<script type='text/javascript'>
  window.BOOTSTRAP.page = <%= @page.to_json.html_safe %>;
</script>

<%= content_for :breadcrumb do %>
  <%= link_to 'Root', :root %>
  <%= link_to @namespace, @namespace %>
  <%= content_tag :span, @page %>
<% end %>

<%= content_for :contextual do %>
  <%= link_to 'Settings', edit_namespace_page_path(@namespace, @page) %>
  <%= link_to 'Uploads', namespace_page_uploads_path(@namespace, @page), class: 'js-page-uploads' %>
  <%= content_tag :span, 'Saved', class: 'actions__status js-page-status' %>
<% end %>

<% if logged_in? %>
  <% content_for :actions do %>
    <%= link_to material_icon.keyboard_arrow_left, previous_namespace_page_path(@namespace, @page) %>
    <%= link_to material_icon.keyboard_arrow_right, next_namespace_page_path(@namespace, @page) %>
    <%= link_to material_icon.shuffle, random_namespace_pages_path(@namespace) %>

    <%= form_for [@namespace, @page], html: { class: 'utility--align-right' } do |f| %>
      <% if @page.archived? %>
        <%= f.hidden_field :status, value: :active %>
        <%= button_tag class: 'button--clear' do %>
          <%= material_icon.unarchive %>
        <% end %>
      <% else %>
        <%= f.hidden_field :status, value: :archived %>
        <%= button_tag class: 'button--clear' do %>
          <%= material_icon.archive %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<div class='page'>
  <%= form_for [@namespace, @page] do |f| %>
    <%= render "pages/editors/#{@page.mode}", f: f, namespace: @namespace, page: @page %>
  <% end %>
</div>