config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'namespaces#index'

  namespace :api, defaults: { format: 'json' } do
    scope module: :v1 do
      get '', to: 'root#index', as: :root

      resources :namespaces, only: %i[index show] do
        resources :pages, only: %i[index show]
      end
    end
  end

  get 'new' => 'namespaces#new'
  get 'search' => 'search#index'

  # Occupy remaining root namespace
  # (place route declarations above this)

  resources :namespaces, path: '' do
    member do
      get 'edit'
    end

    resources :pages, path: '' do
      collection do
        get 'random'
      end

      member do
        get 'rendered'
        get 'source'
        get 'markdown'
        get 'urls'
        get 'next'
        get 'previous'
      end

      resources :uploads, only: %i[index create]
      resources :versions, only: [:index] do
        member do
          post 'restore'
        end
      end
    end
  end
end

app/controllers/versions_controller.rb
# frozen_string_literal: true

class VersionsController < ApplicationController
  before_filter :find_namespaced_page

  # GET /:namespace_id/:page_id/versions
  def index
    @versions = @page.versions.unscope(:order).order(created_at: :desc)
  end

  # POST /:namespace_id/:page_id/versions/:id
  def restore
    @page = @page.versions.find(params[:id]).reify
    if @page.save
      redirect_to namespace_page_path(@namespace, @page), notice: 'Restored'
    else
      redirect :back
    end
  end

  private

  def find_namespaced_page
    @namespace = Namespace.find_by_slug!(params[:namespace_id])
    authenticate! if @namespace.locked?
    @page = @namespace.pages.includes(:uploads).find_by_slug!(params[:page_id])
  rescue StandardError
    redirect_to new_namespace_page_path(params[:namespace_id], id: params[:page_id])
  end
end

app/views/versions/index.html.erb
<% content_for(:title) { "Versions of #{@page.title}" } %>

<%= content_for :breadcrumb do %>
  <%= link_to 'Root', :root %>
  <%= link_to @namespace, @namespace %>
  <%= content_tag :span, @page %>
<% end %>

<%= content_for :contextual do %>
  <%= link_to 'Show', namespace_page_path(@namespace, @page) %>
  <%= link_to 'Edit', edit_namespace_page_path(@namespace, @page), class: 'js-page-edit' %>
<% end %>

<% Differ.format = :html %>
<% @versions.each do |version| %>
  <div class='page-version'>
    <h1>
      <%= time_ago_in_words version.created_at %> ago
    </h1>

    <div class='page-version-actions'>
      <%= button_to 'Restore', restore_namespace_page_version_path(@namespace, @page, version), method: :post %>
    </div>

    <%= Differ.diff(*version.changeset[:content].reverse).to_s.html_safe %>
  </div>
<% end %>