config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'namespaces#index'

  namespace :api, defaults: { format: 'json' } do
    scope module: :v1 do
      get '', to: 'root#index', as: :root

      resources :namespaces, only: %i[index show] do
        resources :pages, only: %i[index show]
      end
    end
  end

  get 'new' => 'namespaces#new'
  get 'search' => 'search#index'

  # Occupy remaining root namespace
  # (place route declarations above this)

  resources :namespaces, path: '' do
    member do
      get 'edit'
    end

    resources :pages, path: '' do
      collection do
        get 'random'
      end

      member do
        get 'rendered'
        get 'source'
        get 'markdown'
        get 'urls'
        get 'next'
        get 'previous'
      end

      resources :uploads, only: %i[index create]
      resources :versions, only: [:index] do
        member do
          post 'restore'
        end
      end
    end
  end
end

app/views/pages/editors/_html.html.erb
<div class='page-html js-page-editor'>
  <div class='page-html__editor'>
    <%= f.text_area :html, rows: 20, class: 'js-page-editor__input' %>
  </div>
  <div class='page-html__preview'>
    <iframe class='js-page-editor__preview' src='<%= rendered_namespace_page_path(namespace, page) %>'></iframe>
  </div>
</div>

app/views/pages/editors/_plain.html.erb
<%= f.text_area :content, rows: 20, class: 'js-page-editor' %>

app/views/pages/editors/_wysiwyg.html.erb
<div class='js-page-editor' data-url='<%= url_for [@namespace, @page] %>'>
  <%= page.html.try(:html_safe) unless page.delta.present? %>
</div>